// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace HAPPYWeb.model
{
    public partial class DB_HAPPYContext : DbContext
    {
        public DB_HAPPYContext()
        {
        }

        public DB_HAPPYContext(DbContextOptions<DB_HAPPYContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Tbmarca> Tbmarca { get; set; }
        public virtual DbSet<Tboficial> Tboficial { get; set; }
        public virtual DbSet<Tbprodutos> Tbprodutos { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseSqlServer("Data Source=DESKTOP-N5F1NG4\\sqlexpress;Initial Catalog=DB_HAPPY;User ID=sa;Password=sa123");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Tbmarca>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedNever();
            });

            modelBuilder.Entity<Tboficial>(entity =>
            {
                entity.Property(e => e.Codigo).ValueGeneratedNever();
            });

            modelBuilder.Entity<Tbprodutos>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedNever();

                entity.HasOne(d => d.IdMarcaNavigation)
                    .WithMany(p => p.Tbprodutos)
                    .HasForeignKey(d => d.IdMarca)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_TBProdutos_TBMarca");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}