// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HAPPYWeb.model
{
    [Table("TBOficial")]
    public partial class Tboficial
    {
        [Key]
        [Display(Name = "Código")]
        [Required(ErrorMessage = "Informe o código.")]

        public int Codigo { get; set; }


        [Required(ErrorMessage = "Informe o nome.")]
        [StringLength(30)]
        [Unicode(false)]
        public string Nome { get; set; }


        [Required(ErrorMessage = "Informe o CPF.")]
        [Column("CPF")]
        [StringLength(11)]
        [Unicode(false)]
        [Display(Name = "CPF")]
        public string Cpf { get; set; }


        [Required(ErrorMessage = "Informe o endereço.")]
        [StringLength(25)]
        [Unicode(false)]
        [Display(Name = "Endereço")]
        public string Endereco { get; set; }


        [Required(ErrorMessage = "Informe o bairro.")]
        [StringLength(25)]
        [Unicode(false)]
        public string Bairro { get; set; }


        [Required(ErrorMessage = "Informe a cidade.")]
        [StringLength(20)]
        [Unicode(false)]
        public string Cidade { get; set; }


        [Required(ErrorMessage = "Informe o CEP.")]
        [Column("CEP")]
        [StringLength(8)]
        [Unicode(false)]
        [Display(Name = "CEP")]
        public string Cep { get; set; }


        [Required(ErrorMessage = "Informe o telefone.")]
        [StringLength(11)]
        [Unicode(false)]
        public string Telefone { get; set; }


        [Required(ErrorMessage = "Informe o e-mail.")]
        [StringLength(50)]
        [Unicode(false)]
        [Display(Name = "E-mail")]
        [RegularExpression(".+\\@.+\\..+", ErrorMessage = "Informe um e-mail válido.")]
        public string Email { get; set; }


        [Required(ErrorMessage = "Informe o cargo atual.")]
        [StringLength(20)]
        [Unicode(false)]
        public string Cargo { get; set; }
    }
}